# Generated by Django 4.0 on 2022-03-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Duedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
